// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD48OFbgNP2kyq7aceO72xmsNlm5tI-66g',
    appId: '1:696996187495:web:5e1d301b433852a65233c2',
    messagingSenderId: '696996187495',
    projectId: 'todolist-60d9b',
    authDomain: 'todolist-60d9b.firebaseapp.com',
    storageBucket: 'todolist-60d9b.appspot.com',
    measurementId: 'G-YDF9EKSV4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDratbVdfkQ4QFZjFPhV2dnhh9rf_5-6g0',
    appId: '1:696996187495:android:f5d7c53f8a9580a85233c2',
    messagingSenderId: '696996187495',
    projectId: 'todolist-60d9b',
    storageBucket: 'todolist-60d9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiZDn9Ov764vAerQh9F7DF0pVU-CEAfAE',
    appId: '1:696996187495:ios:3fc9b983aa50fd885233c2',
    messagingSenderId: '696996187495',
    projectId: 'todolist-60d9b',
    storageBucket: 'todolist-60d9b.appspot.com',
    iosClientId: '696996187495-campme0j2nao4gmusfnohrong55p383b.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiZDn9Ov764vAerQh9F7DF0pVU-CEAfAE',
    appId: '1:696996187495:ios:fa8aabcf831d53db5233c2',
    messagingSenderId: '696996187495',
    projectId: 'todolist-60d9b',
    storageBucket: 'todolist-60d9b.appspot.com',
    iosClientId: '696996187495-hi29v63e1vgivu42u0e6cc2mr402ivgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp.RunnerTests',
  );
}
